# Generated by Django 4.2 on 2023-04-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='gender',
        ),
        migrations.AddField(
            model_name='words',
            name='pinyin',
            field=models.CharField(default='default', max_length=30, verbose_name='Pinyin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='translation',
            field=models.CharField(default='default', max_length=30, verbose_name='Translation'),
            preserve_default=False,
        ),
    ]
